package entity;
// Generated Feb 5, 2017 7:41:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer proId;
     private SubCatagory subCatagory;
     private String proName;
     private int proQty;
     private double proPrice;
     private String proUrl;
     private String proDesc;
     private Set proOrders = new HashSet(0);
     private Set proOrderDetailses = new HashSet(0);

    public Product() {
    }

	
    public Product(SubCatagory subCatagory, String proName, int proQty, double proPrice, String proUrl, String proDesc) {
        this.subCatagory = subCatagory;
        this.proName = proName;
        this.proQty = proQty;
        this.proPrice = proPrice;
        this.proUrl = proUrl;
        this.proDesc = proDesc;
    }
    public Product(SubCatagory subCatagory, String proName, int proQty, double proPrice, String proUrl, String proDesc, Set proOrders, Set proOrderDetailses) {
       this.subCatagory = subCatagory;
       this.proName = proName;
       this.proQty = proQty;
       this.proPrice = proPrice;
       this.proUrl = proUrl;
       this.proDesc = proDesc;
       this.proOrders = proOrders;
       this.proOrderDetailses = proOrderDetailses;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public SubCatagory getSubCatagory() {
        return this.subCatagory;
    }
    
    public void setSubCatagory(SubCatagory subCatagory) {
        this.subCatagory = subCatagory;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public int getProQty() {
        return this.proQty;
    }
    
    public void setProQty(int proQty) {
        this.proQty = proQty;
    }
    public double getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(double proPrice) {
        this.proPrice = proPrice;
    }
    public String getProUrl() {
        return this.proUrl;
    }
    
    public void setProUrl(String proUrl) {
        this.proUrl = proUrl;
    }
    public String getProDesc() {
        return this.proDesc;
    }
    
    public void setProDesc(String proDesc) {
        this.proDesc = proDesc;
    }
    public Set getProOrders() {
        return this.proOrders;
    }
    
    public void setProOrders(Set proOrders) {
        this.proOrders = proOrders;
    }
    public Set getProOrderDetailses() {
        return this.proOrderDetailses;
    }
    
    public void setProOrderDetailses(Set proOrderDetailses) {
        this.proOrderDetailses = proOrderDetailses;
    }




}


