package entity;
// Generated Feb 5, 2017 7:41:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SubCatagory generated by hbm2java
 */
public class SubCatagory  implements java.io.Serializable {


     private Integer subCatId;
     private Catagory catagory;
     private String subCatName;
     private String subCatDesc;
     private Set products = new HashSet(0);

    public SubCatagory() {
    }

	
    public SubCatagory(Catagory catagory, String subCatName, String subCatDesc) {
        this.catagory = catagory;
        this.subCatName = subCatName;
        this.subCatDesc = subCatDesc;
    }
    public SubCatagory(Catagory catagory, String subCatName, String subCatDesc, Set products) {
       this.catagory = catagory;
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.products = products;
    }
   
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }
    public Catagory getCatagory() {
        return this.catagory;
    }
    
    public void setCatagory(Catagory catagory) {
        this.catagory = catagory;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


